DROP DATABASE IF EXISTS bestWestern;
CREATE DATABASE bestWestern;
use bestWestern;
DROP TABLE IF EXISTS Users;
DROP TABLE  IF EXISTS Messages;
DROP TABLE  IF EXISTS Hostels;
DROP TABLE  IF EXISTS Users_hostels;
CREATE TABLE Users (
    id INTEGER UNSIGNED NOT NULL AUTO_INCREMENT,
    pseudo VARCHAR(40) NOT NULL,
    email VARCHAR(40) NOT NULL,
    address VARCHAR(80) NOT NULL,
    password BINARY(60) NOT NULL,
    ambassador BOOLEAN NOT NULL DEFAULT FALSE,
    reward INTEGER,
    PRIMARY KEY (id)
);

CREATE TABLE Messages (
    id INTEGER UNSIGNED NOT NULL AUTO_INCREMENT,
    fromUser INTEGER UNSIGNED NOT NULL,
    toUser INTEGER UNSIGNED NOT NULL,
	  content TEXT,
	  FOREIGN KEY (fromUser) REFERENCES Users(id),
	  FOREIGN KEY (toUser) REFERENCES Users(id),
    PRIMARY KEY (id)
);

CREATE TABLE Hostels (
    id INTEGER UNSIGNED NOT NULL AUTO_INCREMENT,
    address VARCHAR(80) NOT NULL,
    PRIMARY KEY (id)
);

CREATE TABLE Users_hostels (
    id SMALLINT UNSIGNED NOT NULL AUTO_INCREMENT,
    user_id INTEGER UNSIGNED NOT NULL,
	  hostel_id INTEGER UNSIGNED NOT NULL,
    PRIMARY KEY (id),
	FOREIGN KEY (user_id) REFERENCES Users(id),
	FOREIGN KEY (hostel_id) REFERENCES Hostels(id)
);